// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxxctfbbjxiensybniae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14eGN0ZmJianhpZW5zeWJuaWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NTk4OTcsImV4cCI6MjA2MzAzNTg5N30.VT_P9L_w3dL6jClxdBaVZi2jV6YwJXTMho7406Jk2HI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);